version: "3.8"

services:
  server:
    container_name: "gitsast-api"
    image: gitsast
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=${APP_ENV}
    command: sh -c "/app/entrypoint.sh"
  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "gitsast"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
