version: "3.8"

services:
  server:
    image: gitsast
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=${APP_ENV}
    command: sh -c "/app/entrypoint.sh"
  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "gitsast"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
