// Code generated by MockGen. DO NOT EDIT.
// Source: internal/queue/task/analyzer/git/client.go

// Package testutil is a generated GoMock package.
package testutil

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// GetPathsFromRemoteURL mocks base method.
func (m *MockIClient) GetPathsFromRemoteURL(tmpDir, remoteURL string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPathsFromRemoteURL", tmpDir, remoteURL)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPathsFromRemoteURL indicates an expected call of GetPathsFromRemoteURL.
func (mr *MockIClientMockRecorder) GetPathsFromRemoteURL(tmpDir, remoteURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPathsFromRemoteURL", reflect.TypeOf((*MockIClient)(nil).GetPathsFromRemoteURL), tmpDir, remoteURL)
}
